DROP_TABLES=('DROP TABLE IF EXISTS temporal; '
'DROP TABLE IF EXISTS temporal_inflacion; '
'DROP TABLE IF EXISTS temporalISO3166; '
'DROP TABLE IF EXISTS reporte; '
'DROP TABLE IF EXISTS pais; '
'DROP TABLE IF EXISTS dimension; '
'DROP TABLE IF EXISTS fecha; '
'DROP TABLE IF EXISTS region; '
'DROP TABLE IF EXISTS periodicidad; '
'DROP TABLE IF EXISTS sub_region; ')

TEMPORAL_CREATION=(
    'CREATE TABLE temporalISO3166('
    'country_name varchar(250), '
    'alpha3 varchar(10), '
    'country_code BIGINT, '
    'region varchar(250), '
    'region_code BIGINT, '
    'sub_region varchar(250),'
    'sub_region_code BIGINT ); '
    'CREATE TABLE temporal('
    'series_name varchar(250), '
    'country_name varchar(250), '
    'country_code varchar(20), '
    '`1990` FLOAT, '
    '`2000` FLOAT, '
    '`2001` FLOAT, '
    '`2002` FLOAT, '
    '`2003` FLOAT, '
    '`2004` FLOAT, '
    '`2005` FLOAT, '
    '`2006` FLOAT, '
    '`2007` FLOAT, '
    '`2008` FLOAT, '
    '`2009` FLOAT, '
    '`2010` FLOAT, '
    '`2011` FLOAT, '
    '`2012` FLOAT, '
    '`2013` FLOAT, '
    '`2014` FLOAT, '
    '`2015` FLOAT, '
    '`2016` FLOAT, '
    '`2017` FLOAT, '
    '`2018` FLOAT, '
    '`2019` FLOAT, '
    '`2020` FLOAT, '
    '`2021` FLOAT);'
    'CREATE TABLE temporal_inflacion('
    'series_name varchar(250), '
    'country_name varchar(250), '
    'country_code varchar(20), '
    '`1990` FLOAT, '
    '`2000` FLOAT, '
    '`2001` FLOAT, '
    '`2002` FLOAT, '
    '`2003` FLOAT, '
    '`2004` FLOAT, '
    '`2005` FLOAT, '
    '`2006` FLOAT, '
    '`2007` FLOAT, '
    '`2008` FLOAT, '
    '`2009` FLOAT, '
    '`2010` FLOAT, '
    '`2011` FLOAT, '
    '`2012` FLOAT, '
    '`2013` FLOAT, '
    '`2014` FLOAT, '
    '`2015` FLOAT, '
    '`2016` FLOAT, '
    '`2017` FLOAT, '
    '`2018` FLOAT, '
    '`2019` FLOAT, '
    '`2020` FLOAT, '
    '`2021` FLOAT);')

COLLATE=('ALTER TABLE temporal CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;'
'ALTER TABLE temporal_inflacion CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;')

CREATE_MODEL=(
' CREATE TABLE `dimension` ('
    '`id` int(11) NOT NULL, '
    '`descripcion` varchar(200) NOT NULL '
') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; '
'CREATE TABLE `fecha` ('
  '`id` int(11) NOT NULL,'
  '`anio` int(11) NOT NULL'
') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;'
'CREATE TABLE `pais` ('
  '`id` int(11) NOT NULL,'
  '`id_region` int(11) NOT NULL,'
  '`id_sub_region` int(11) NOT NULL,'
  '`id_intermediate_region` int(11) NOT NULL,'
  '`nombre` varchar(200) NOT NULL'
') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;'
'CREATE TABLE `periodicidad` ('
  '`id` int(11) NOT NULL,'
  '`descripcion` varchar(250) NOT NULL'
') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;'
'CREATE TABLE `region` ('
  '`id` int(11) NOT NULL,'
  '`nombre` varchar(250) NOT NULL'
') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;'
'CREATE TABLE `reporte` ('
  '`id` int(11) NOT NULL,'
  '`inflacion` float NOT NULL,'
  '`PIB` float NOT NULL,'
  '`id_pais` int(11) NOT NULL,'
  '`id_periodicidad` int(11) NOT NULL,'
  '`id_dimension` int(11) NOT NULL,'
  '`id_fecha` int(11) NOT NULL'
') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;'
'CREATE TABLE `sub_region` ('
  '`id` int(11) NOT NULL,'
  '`nombre` varchar(250) NOT NULL'
') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;'
'ALTER TABLE `dimension`'
  'ADD PRIMARY KEY (`id`);'
  'ALTER TABLE `fecha`'
  'ADD PRIMARY KEY (`id`);'
  'ALTER TABLE `pais`'
  'ADD PRIMARY KEY (`id`),'
  'ADD UNIQUE KEY `id_region` (`id_region`,`id_sub_region`,`id_intermediate_region`),'
  'ADD KEY `id_sub_region` (`id_sub_region`),'
  'ADD KEY `id_intermediate_region` (`id_intermediate_region`);'
  'ALTER TABLE `periodicidad`'
  'ADD PRIMARY KEY (`id`);'
  'ALTER TABLE `region`'
  'ADD PRIMARY KEY (`id`);'
'ALTER TABLE `reporte`'
  'ADD PRIMARY KEY (`id`),'
  'ADD UNIQUE KEY `id_pais` (`id_pais`,`id_periodicidad`,`id_dimension`,`id_fecha`),'
  'ADD KEY `id_periodicidad` (`id_periodicidad`),'
  'ADD KEY `id_fecha` (`id_fecha`),'
  'ADD KEY `id_dimension` (`id_dimension`);'
  'ALTER TABLE `sub_region`'
  'ADD PRIMARY KEY (`id`);'
  'ALTER TABLE `dimension`'
  'MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;'
  'ALTER TABLE `fecha`'
  'MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;'
  'ALTER TABLE `periodicidad`'
  'MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;'
  'ALTER TABLE `reporte`'
  'MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;'
  'ALTER TABLE `pais`'
  'MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;'
  'ADD CONSTRAINT `pais_ibfk_1` FOREIGN KEY (`id_sub_region`) REFERENCES `sub_region` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,'
  'ADD CONSTRAINT `pais_ibfk_3` FOREIGN KEY (`id_region`) REFERENCES `region` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;'
  'ALTER TABLE `reporte`'
  'ADD CONSTRAINT `reporte_ibfk_1` FOREIGN KEY (`id_periodicidad`) REFERENCES `periodicidad` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,'
  'ADD CONSTRAINT `reporte_ibfk_2` FOREIGN KEY (`id_fecha`) REFERENCES `fecha` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,'
  'ADD CONSTRAINT `reporte_ibfk_3` FOREIGN KEY (`id_dimension`) REFERENCES `dimension` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,'
  'ADD CONSTRAINT `reporte_ibfk_4` FOREIGN KEY (`id_pais`) REFERENCES `pais` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;'
)

FILL_MODEL=(
    'INSERT INTO region(id, nombre)'
    'SELECT DISTINCT region_code, region  FROM temporalISO3166 WHERE region_code != 0 ORDER BY region  ASC;'
)

REGION=('INSERT INTO region(id, nombre)'
'SELECT DISTINCT region_code, region  FROM temporalISO3166 WHERE region_code != 0 ORDER BY region  ASC;')

SUB_REGION=('INSERT INTO sub_region (id, nombre)'
'SELECT DISTINCT sub_region_code, sub_region  FROM temporalISO3166 WHERE region_code != 0 ORDER BY sub_region  ASC ;')

FECHA=('INSERT INTO fecha (anio) '
'SELECT COLUMN_NAME '
'FROM INFORMATION_SCHEMA.COLUMNS '
'WHERE TABLE_NAME = \'temporal_inflacion\' AND COLUMN_NAME REGEXP \'^[0-9]+$\' ORDER BY COLUMN_NAME ASC; ')

DIMENSION=('INSERT INTO dimension (descripcion) VALUES (\'Porcentaje\');')

PERIODICIDAD=('INSERT INTO periodicidad (descripcion) VALUES (\'Anual\');')
PAIS=('INSERT INTO pais '
'SELECT DISTINCT ti.country_code, r.id, sr.id, ti.country_name FROM temporalISO3166 ti, region r, sub_region sr '
'WHERE ti.region_code = r.id AND sr.id = ti.sub_region_code ORDER BY ti.country_name ASC; ')


# 'INSERT INTO sub_region (id, nombre)'
#     'SELECT DISTINCT sub_region_code, sub_region  FROM temporalISO3166 WHERE region_code != 0 ORDER BY sub_region  ASC ;'
#     'INSERT INTO fecha (anio)'
#     'SELECT COLUMN_NAME'
#     'FROM INFORMATION_SCHEMA.COLUMNS'
#     'WHERE TABLE_NAME = N\'temporal_inflacion\' AND ISNUMERIC(COLUMN_NAME) = 1 ORDER BY COLUMN_NAME ASC;'
#     'INSERT INTO dimension (descripcion) VALUES (\'Porcentaje\');'
#     'INSERT INTO periodicidad (descripcion) VALUES (\'Anual\');'
#     'INSERT INTO pais'
#     'SELECT DISTINCT ti.country_code, r.id, sr.id, ti.country_name FROM temporalISO3166 ti, region r, sub_region sr '
#     'WHERE ti.region_code = r.id AND sr.id = ti.sub_region_code ORDER BY ti.country_name ASC;'